### PR TITLE
i18n - pulling from tx

### PR DESCRIPTION
**Pull request by upadhyeammit**

### CODE REVIEW

**Comment by masayag** [comment]
@shiramax Could you check if the build failure is related to foreman's build ? The failure complains about missing postgresql gem which shouldn't be a requirement of this plugin:
```
$ bundle exec rake db:migrate RAILS_ENV=test
rake aborted!
LoadError: Error loading the 'postgresql' Active Record adapter. Missing a gem it depends on? pg is not part of the bundle. Add it to your Gemfile.
/home/travis/.rvm/gems/ruby-2.5.8/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:4:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.5.8/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `require'
```
https://travis-ci.com/github/theforeman/foreman_kubevirt/builds/169010848

**Comment by upadhyeammit** [comment]
@masayag @shiramax can we merge this one ? Its pending since long time.

**Comment by shiramax** [comment]
@upadhyeammit Sorry for keeping you waiting, I will review it today

**Comment by shiramax** [comment]
@upadhyeammit can you please rebase this one?

**Pull request merged**
