### PR TITLE
Translation improvements

### PR DESCRIPTION
**Pull request by stejskalleos**
* Extract missing strings for the translations
* Fix interpolations in strings
* Update config for the transifex-cli
* Update *.po files

### CODE REVIEW

**Comment by stejskalleos** [comment]
@adamruzicka Review please

**Comment by adamruzicka** [comment]
I don't see the mo files being added here?

**Comment by stejskalleos** [comment]
Added `mo` files

**Review by adamruzicka — APPROVED** [review]
lgtm

**Pull request merged**
